#define SYSCFG_BASE   0x58000400

/* EXTICR */
#define SYSCFG_EXTICR_GPIOA   0
#define SYSCFG_EXTICR_GPIOB   1
#define SYSCFG_EXTICR_GPIOC   2
#define SYSCFG_EXTICR_GPIOD   3
#define SYSCFG_EXTICR_GPIOE   4
#define SYSCFG_EXTICR_GPIOF   5
#define SYSCFG_EXTICR_GPIOG   6
#define SYSCFG_EXTICR_GPIOH   7
#define SYSCFG_EXTICR_GPIOI   8
#define SYSCFG_EXTICR_GPIOJ   9
#define SYSCFG_EXTICR_GPIOK   10

/* EXTICR4 */
#define SYSCFG_EXTICR4_OFFSET   0x14
#define SYSCFG_EXTICR4          (SYSCFG_BASE + SYSCFG_EXTICR4_OFFSET)

#define SYSCFG_EXTICR4_EXTI12  0
#define SYSCFG_EXTICR4_EXTI13  4
#define SYSCFG_EXTICR4_EXTI14  8
#define SYSCFG_EXTICR4_EXTI15  12
