/* TIM_CR1 */
#define TIM_CR1_OFFSET  0x00

#define TIM_CR1_CEN_INDEX     0
#define TIM_CR1_CEN_ENABLED   (1 << TIM_CR1_CEN_INDEX)

/* TIM_DIER */
#define TIM_DIER_OFFSET   0x0C

#define TIM_DIER_UIE_INDEX    0
#define TIM_DIER_UIE_ENABLED  (1 << TIM_DIER_UIE_INDEX)

/* TIM_SR */
#define TIM_SR_OFFSET   0x10

#define TIM_SR_UIF_INDEX    0
#define TIM_SR_UIF_PENDING  (1 << TIM_SR_UIF_INDEX)
#define TIM_SR_UIF_CLEARED  0

/* TIM_EGR */
#define TIM_EGR_OFFSET  0x14

#define TIM_EGR_UG_INDEX    0
#define TIM_EGR_UG_REINIT   (1 << TIM_EGR_UG_INDEX)

#define TIM_PSC_OFFSET  0x28
#define TIM_ARR_OFFSET  0x2C

/* TIM6 */
#define TIM6_BASE   0x40001000
#define TIM6_CR1    (TIM6_BASE + TIM_CR1_OFFSET)
#define TIM6_DIER   (TIM6_BASE + TIM_DIER_OFFSET)
#define TIM6_SR     (TIM6_BASE + TIM_SR_OFFSET)
#define TIM6_EGR    (TIM6_BASE + TIM_EGR_OFFSET)
#define TIM6_PSC    (TIM6_BASE + TIM_PSC_OFFSET)
#define TIM6_ARR    (TIM6_BASE + TIM_ARR_OFFSET)
